# Dummy YAML for Hello World
name: Sequential WorkFlow
on: workflow_dispatch
jobs:
  myFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: GreetUser
        run: echo "HowDay User"
      - name: EndOfWork
        run: echo "bye bye User"
  mySecondJob:
    runs-on: ubuntu-latest
    steps:
      - name: GreetUser
        run: | 
          echo "Wow"
          echo "...and WOOOOOW"        
